// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.28.3
// source: shared/protocol/executor/v1/executor.proto

package executorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NullValue represents a JSON null.
type NullValue int32

const (
	NullValue_NULL_VALUE NullValue = 0
)

// Enum value maps for NullValue.
var (
	NullValue_name = map[int32]string{
		0: "NULL_VALUE",
	}
	NullValue_value = map[string]int32{
		"NULL_VALUE": 0,
	}
)

func (x NullValue) Enum() *NullValue {
	p := new(NullValue)
	*p = x
	return p
}

func (x NullValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NullValue) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_protocol_executor_v1_executor_proto_enumTypes[0].Descriptor()
}

func (NullValue) Type() protoreflect.EnumType {
	return &file_shared_protocol_executor_v1_executor_proto_enumTypes[0]
}

func (x NullValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NullValue.Descriptor instead.
func (NullValue) EnumDescriptor() ([]byte, []int) {
	return file_shared_protocol_executor_v1_executor_proto_rawDescGZIP(), []int{0}
}

// InitializeRequest is sent by N.O.R.E. to negotiate the protocol and
// exchange executor identity.
type InitializeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// protocol_version is the version of the executor protocol the runtime
	// supports (e.g. "neuron/executor-v1"). The executor must reject
	// incompatible versions.
	ProtocolVersion string `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// metadata carries executor identity and configuration.
	// Known keys: "executor_type", "executor_version", "execution_id".
	Metadata      map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_shared_protocol_executor_v1_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protocol_executor_v1_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_shared_protocol_executor_v1_executor_proto_rawDescGZIP(), []int{0}
}

func (x *InitializeRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *InitializeRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// InitializeResponse is returned by the executor after successful initialization.
type InitializeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// protocol_version is the version the executor supports. The runtime
	// must verify this matches or is compatible with the requested version.
	ProtocolVersion string `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// capabilities declares what this executor supports.
	// Known values: "concurrent", "streaming", "cancellation".
	Capabilities []string `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// metadata carries executor-specific identity information.
	Metadata      map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeResponse) Reset() {
	*x = InitializeResponse{}
	mi := &file_shared_protocol_executor_v1_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResponse) ProtoMessage() {}

func (x *InitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protocol_executor_v1_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResponse.ProtoReflect.Descriptor instead.
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return file_shared_protocol_executor_v1_executor_proto_rawDescGZIP(), []int{1}
}

func (x *InitializeResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *InitializeResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *InitializeResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ExecuteRequest carries one execution request to the executor.
type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// execution_id is a unique identifier for this execution. The executor
	// may use it for logging and correlation.
	ExecutionId string `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	// input carries the resolved execution input for the service. Keys map
	// to the executor's declared inputs.
	Input map[string]*Value `protobuf:"bytes,2,rep,name=input,proto3" json:"input,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// timeout_ms is the maximum time the executor should spend on this
	// execution. The executor should respect this deadline and return a
	// timeout error if exceeded. A value of 0 means no timeout.
	TimeoutMs int64 `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	// correlation_id links this execution to a parent execution or request chain.
	CorrelationId string `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_shared_protocol_executor_v1_executor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protocol_executor_v1_executor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_shared_protocol_executor_v1_executor_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecuteRequest) GetInput() map[string]*Value {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ExecuteRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *ExecuteRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// ExecuteResponse carries the result of one execution.
type ExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// output carries the results of the execution. Keys map to the
	// executor's declared outputs.
	Output map[string]*Value `protobuf:"bytes,1,rep,name=output,proto3" json:"output,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// error, when non-empty, records a controlled failure. The executor
	// may still return this with a successful gRPC status; the runtime
	// treats a non-empty error as an execution failure.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// metadata carries execution-specific metadata (e.g. timing, trace IDs).
	Metadata      map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_shared_protocol_executor_v1_executor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protocol_executor_v1_executor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_shared_protocol_executor_v1_executor_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteResponse) GetOutput() map[string]*Value {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// HealthRequest is sent periodically by the runtime.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_shared_protocol_executor_v1_executor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protocol_executor_v1_executor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_shared_protocol_executor_v1_executor_proto_rawDescGZIP(), []int{4}
}

// HealthResponse reports executor health status.
type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ready indicates the executor can accept new requests.
	Ready bool `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	// message provides optional human-readable health information.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// active_executions is the number of currently in-flight executions.
	ActiveExecutions int32 `protobuf:"varint,3,opt,name=active_executions,json=activeExecutions,proto3" json:"active_executions,omitempty"`
	// max_executions is the maximum concurrent executions this executor supports.
	MaxExecutions int32 `protobuf:"varint,4,opt,name=max_executions,json=maxExecutions,proto3" json:"max_executions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_shared_protocol_executor_v1_executor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protocol_executor_v1_executor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_shared_protocol_executor_v1_executor_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthResponse) GetActiveExecutions() int32 {
	if x != nil {
		return x.ActiveExecutions
	}
	return 0
}

func (x *HealthResponse) GetMaxExecutions() int32 {
	if x != nil {
		return x.MaxExecutions
	}
	return 0
}

// ShutdownRequest requests graceful termination.
type ShutdownRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// timeout_ms is the maximum time the runtime will wait for graceful
	// shutdown before forcefully terminating the process.
	TimeoutMs     int64 `protobuf:"varint,1,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_shared_protocol_executor_v1_executor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protocol_executor_v1_executor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_shared_protocol_executor_v1_executor_proto_rawDescGZIP(), []int{6}
}

func (x *ShutdownRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// ShutdownResponse confirms the executor is shutting down.
type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_shared_protocol_executor_v1_executor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protocol_executor_v1_executor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_shared_protocol_executor_v1_executor_proto_rawDescGZIP(), []int{7}
}

// Value is a dynamic value that can represent any JSON-compatible type.
// It mirrors google.protobuf.Value for JSON interop.
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_NullValue
	//	*Value_NumberValue
	//	*Value_StringValue
	//	*Value_BoolValue
	//	*Value_ListValue
	//	*Value_StructValue
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_shared_protocol_executor_v1_executor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protocol_executor_v1_executor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_shared_protocol_executor_v1_executor_proto_rawDescGZIP(), []int{8}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetNullValue() NullValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_NullValue); ok {
			return x.NullValue
		}
	}
	return NullValue_NULL_VALUE
}

func (x *Value) GetNumberValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_NumberValue); ok {
			return x.NumberValue
		}
	}
	return 0
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetListValue() *ListValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_ListValue); ok {
			return x.ListValue
		}
	}
	return nil
}

func (x *Value) GetStructValue() *Struct {
	if x != nil {
		if x, ok := x.Kind.(*Value_StructValue); ok {
			return x.StructValue
		}
	}
	return nil
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_NullValue struct {
	NullValue NullValue `protobuf:"varint,1,opt,name=null_value,json=nullValue,proto3,enum=neuron.executor.v1.NullValue,oneof"`
}

type Value_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,2,opt,name=number_value,json=numberValue,proto3,oneof"`
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_ListValue struct {
	ListValue *ListValue `protobuf:"bytes,5,opt,name=list_value,json=listValue,proto3,oneof"`
}

type Value_StructValue struct {
	StructValue *Struct `protobuf:"bytes,6,opt,name=struct_value,json=structValue,proto3,oneof"`
}

func (*Value_NullValue) isValue_Kind() {}

func (*Value_NumberValue) isValue_Kind() {}

func (*Value_StringValue) isValue_Kind() {}

func (*Value_BoolValue) isValue_Kind() {}

func (*Value_ListValue) isValue_Kind() {}

func (*Value_StructValue) isValue_Kind() {}

// ListValue is a repeated Value.
type ListValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Value               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValue) Reset() {
	*x = ListValue{}
	mi := &file_shared_protocol_executor_v1_executor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValue) ProtoMessage() {}

func (x *ListValue) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protocol_executor_v1_executor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValue.ProtoReflect.Descriptor instead.
func (*ListValue) Descriptor() ([]byte, []int) {
	return file_shared_protocol_executor_v1_executor_proto_rawDescGZIP(), []int{9}
}

func (x *ListValue) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

// Struct is a map of string to Value.
type Struct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]*Value      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Struct) Reset() {
	*x = Struct{}
	mi := &file_shared_protocol_executor_v1_executor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Struct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Struct) ProtoMessage() {}

func (x *Struct) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protocol_executor_v1_executor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Struct.ProtoReflect.Descriptor instead.
func (*Struct) Descriptor() ([]byte, []int) {
	return file_shared_protocol_executor_v1_executor_proto_rawDescGZIP(), []int{10}
}

func (x *Struct) GetFields() map[string]*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

var File_shared_protocol_executor_v1_executor_proto protoreflect.FileDescriptor

const file_shared_protocol_executor_v1_executor_proto_rawDesc = "" +
	"\n" +
	"*shared/protocol/executor/v1/executor.proto\x12\x12neuron.executor.v1\"\xcc\x01\n" +
	"\x11InitializeRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12O\n" +
	"\bmetadata\x18\x02 \x03(\v23.neuron.executor.v1.InitializeRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf2\x01\n" +
	"\x12InitializeResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x12P\n" +
	"\bmetadata\x18\x03 \x03(\v24.neuron.executor.v1.InitializeResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x93\x02\n" +
	"\x0eExecuteRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12C\n" +
	"\x05input\x18\x02 \x03(\v2-.neuron.executor.v1.ExecuteRequest.InputEntryR\x05input\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x03R\ttimeoutMs\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\x1aS\n" +
	"\n" +
	"InputEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.neuron.executor.v1.ValueR\x05value:\x028\x01\"\xd2\x02\n" +
	"\x0fExecuteResponse\x12G\n" +
	"\x06output\x18\x01 \x03(\v2/.neuron.executor.v1.ExecuteResponse.OutputEntryR\x06output\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12M\n" +
	"\bmetadata\x18\x03 \x03(\v21.neuron.executor.v1.ExecuteResponse.MetadataEntryR\bmetadata\x1aT\n" +
	"\vOutputEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.neuron.executor.v1.ValueR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0f\n" +
	"\rHealthRequest\"\x94\x01\n" +
	"\x0eHealthResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x11active_executions\x18\x03 \x01(\x05R\x10activeExecutions\x12%\n" +
	"\x0emax_executions\x18\x04 \x01(\x05R\rmaxExecutions\"0\n" +
	"\x0fShutdownRequest\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x01 \x01(\x03R\ttimeoutMs\"\x12\n" +
	"\x10ShutdownResponse\"\xbb\x02\n" +
	"\x05Value\x12>\n" +
	"\n" +
	"null_value\x18\x01 \x01(\x0e2\x1d.neuron.executor.v1.NullValueH\x00R\tnullValue\x12#\n" +
	"\fnumber_value\x18\x02 \x01(\x01H\x00R\vnumberValue\x12#\n" +
	"\fstring_value\x18\x03 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12>\n" +
	"\n" +
	"list_value\x18\x05 \x01(\v2\x1d.neuron.executor.v1.ListValueH\x00R\tlistValue\x12?\n" +
	"\fstruct_value\x18\x06 \x01(\v2\x1a.neuron.executor.v1.StructH\x00R\vstructValueB\x06\n" +
	"\x04kind\">\n" +
	"\tListValue\x121\n" +
	"\x06values\x18\x01 \x03(\v2\x19.neuron.executor.v1.ValueR\x06values\"\x9e\x01\n" +
	"\x06Struct\x12>\n" +
	"\x06fields\x18\x01 \x03(\v2&.neuron.executor.v1.Struct.FieldsEntryR\x06fields\x1aT\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.neuron.executor.v1.ValueR\x05value:\x028\x01*\x1b\n" +
	"\tNullValue\x12\x0e\n" +
	"\n" +
	"NULL_VALUE\x10\x002\xea\x02\n" +
	"\x0fExecutorService\x12[\n" +
	"\n" +
	"Initialize\x12%.neuron.executor.v1.InitializeRequest\x1a&.neuron.executor.v1.InitializeResponse\x12R\n" +
	"\aExecute\x12\".neuron.executor.v1.ExecuteRequest\x1a#.neuron.executor.v1.ExecuteResponse\x12O\n" +
	"\x06Health\x12!.neuron.executor.v1.HealthRequest\x1a\".neuron.executor.v1.HealthResponse\x12U\n" +
	"\bShutdown\x12#.neuron.executor.v1.ShutdownRequest\x1a$.neuron.executor.v1.ShutdownResponseBGZEgithub.com/Muhammad-Jay/neuron/shared/protocol/executor/v1;executorv1b\x06proto3"

var (
	file_shared_protocol_executor_v1_executor_proto_rawDescOnce sync.Once
	file_shared_protocol_executor_v1_executor_proto_rawDescData []byte
)

func file_shared_protocol_executor_v1_executor_proto_rawDescGZIP() []byte {
	file_shared_protocol_executor_v1_executor_proto_rawDescOnce.Do(func() {
		file_shared_protocol_executor_v1_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_protocol_executor_v1_executor_proto_rawDesc), len(file_shared_protocol_executor_v1_executor_proto_rawDesc)))
	})
	return file_shared_protocol_executor_v1_executor_proto_rawDescData
}

var file_shared_protocol_executor_v1_executor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shared_protocol_executor_v1_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_shared_protocol_executor_v1_executor_proto_goTypes = []any{
	(NullValue)(0),             // 0: neuron.executor.v1.NullValue
	(*InitializeRequest)(nil),  // 1: neuron.executor.v1.InitializeRequest
	(*InitializeResponse)(nil), // 2: neuron.executor.v1.InitializeResponse
	(*ExecuteRequest)(nil),     // 3: neuron.executor.v1.ExecuteRequest
	(*ExecuteResponse)(nil),    // 4: neuron.executor.v1.ExecuteResponse
	(*HealthRequest)(nil),      // 5: neuron.executor.v1.HealthRequest
	(*HealthResponse)(nil),     // 6: neuron.executor.v1.HealthResponse
	(*ShutdownRequest)(nil),    // 7: neuron.executor.v1.ShutdownRequest
	(*ShutdownResponse)(nil),   // 8: neuron.executor.v1.ShutdownResponse
	(*Value)(nil),              // 9: neuron.executor.v1.Value
	(*ListValue)(nil),          // 10: neuron.executor.v1.ListValue
	(*Struct)(nil),             // 11: neuron.executor.v1.Struct
	nil,                        // 12: neuron.executor.v1.InitializeRequest.MetadataEntry
	nil,                        // 13: neuron.executor.v1.InitializeResponse.MetadataEntry
	nil,                        // 14: neuron.executor.v1.ExecuteRequest.InputEntry
	nil,                        // 15: neuron.executor.v1.ExecuteResponse.OutputEntry
	nil,                        // 16: neuron.executor.v1.ExecuteResponse.MetadataEntry
	nil,                        // 17: neuron.executor.v1.Struct.FieldsEntry
}
var file_shared_protocol_executor_v1_executor_proto_depIdxs = []int32{
	12, // 0: neuron.executor.v1.InitializeRequest.metadata:type_name -> neuron.executor.v1.InitializeRequest.MetadataEntry
	13, // 1: neuron.executor.v1.InitializeResponse.metadata:type_name -> neuron.executor.v1.InitializeResponse.MetadataEntry
	14, // 2: neuron.executor.v1.ExecuteRequest.input:type_name -> neuron.executor.v1.ExecuteRequest.InputEntry
	15, // 3: neuron.executor.v1.ExecuteResponse.output:type_name -> neuron.executor.v1.ExecuteResponse.OutputEntry
	16, // 4: neuron.executor.v1.ExecuteResponse.metadata:type_name -> neuron.executor.v1.ExecuteResponse.MetadataEntry
	0,  // 5: neuron.executor.v1.Value.null_value:type_name -> neuron.executor.v1.NullValue
	10, // 6: neuron.executor.v1.Value.list_value:type_name -> neuron.executor.v1.ListValue
	11, // 7: neuron.executor.v1.Value.struct_value:type_name -> neuron.executor.v1.Struct
	9,  // 8: neuron.executor.v1.ListValue.values:type_name -> neuron.executor.v1.Value
	17, // 9: neuron.executor.v1.Struct.fields:type_name -> neuron.executor.v1.Struct.FieldsEntry
	9,  // 10: neuron.executor.v1.ExecuteRequest.InputEntry.value:type_name -> neuron.executor.v1.Value
	9,  // 11: neuron.executor.v1.ExecuteResponse.OutputEntry.value:type_name -> neuron.executor.v1.Value
	9,  // 12: neuron.executor.v1.Struct.FieldsEntry.value:type_name -> neuron.executor.v1.Value
	1,  // 13: neuron.executor.v1.ExecutorService.Initialize:input_type -> neuron.executor.v1.InitializeRequest
	3,  // 14: neuron.executor.v1.ExecutorService.Execute:input_type -> neuron.executor.v1.ExecuteRequest
	5,  // 15: neuron.executor.v1.ExecutorService.Health:input_type -> neuron.executor.v1.HealthRequest
	7,  // 16: neuron.executor.v1.ExecutorService.Shutdown:input_type -> neuron.executor.v1.ShutdownRequest
	2,  // 17: neuron.executor.v1.ExecutorService.Initialize:output_type -> neuron.executor.v1.InitializeResponse
	4,  // 18: neuron.executor.v1.ExecutorService.Execute:output_type -> neuron.executor.v1.ExecuteResponse
	6,  // 19: neuron.executor.v1.ExecutorService.Health:output_type -> neuron.executor.v1.HealthResponse
	8,  // 20: neuron.executor.v1.ExecutorService.Shutdown:output_type -> neuron.executor.v1.ShutdownResponse
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_shared_protocol_executor_v1_executor_proto_init() }
func file_shared_protocol_executor_v1_executor_proto_init() {
	if File_shared_protocol_executor_v1_executor_proto != nil {
		return
	}
	file_shared_protocol_executor_v1_executor_proto_msgTypes[8].OneofWrappers = []any{
		(*Value_NullValue)(nil),
		(*Value_NumberValue)(nil),
		(*Value_StringValue)(nil),
		(*Value_BoolValue)(nil),
		(*Value_ListValue)(nil),
		(*Value_StructValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_protocol_executor_v1_executor_proto_rawDesc), len(file_shared_protocol_executor_v1_executor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_protocol_executor_v1_executor_proto_goTypes,
		DependencyIndexes: file_shared_protocol_executor_v1_executor_proto_depIdxs,
		EnumInfos:         file_shared_protocol_executor_v1_executor_proto_enumTypes,
		MessageInfos:      file_shared_protocol_executor_v1_executor_proto_msgTypes,
	}.Build()
	File_shared_protocol_executor_v1_executor_proto = out.File
	file_shared_protocol_executor_v1_executor_proto_goTypes = nil
	file_shared_protocol_executor_v1_executor_proto_depIdxs = nil
}
