# nonk8s
apiVersion: neuron/v1
kind: Service

metadata:
  name: customer.validate
  version: 1.0.0
  description: Validate customer information

spec:
  executor:
    type: wasm
    version: 1.0.0
    source: neuron-registry

    config:
      module: customer-validator

  config:
    strict: true

  mappings:
    - name: customer-input
      direction: input
      source: execution.input.customer
      target: customer

    - name: validation-result
      direction: output
      source: result
      target: execution.output.validation

  validation:
    input:
      type: object
      required:
        - customer

    output:
      type: object

  execution:
    mode: wait
    timeout: 5s
    retries: 2
    concurrency: 4