apiVersion: neuron/v1
kind: Connector

metadata:
  name: authorize-to-capture
  version: 1.0.0
  description: Authorized payment flows into capture

from: authorize-payment
to: capture-payment

mappings:
  - target: payment_intent_id
    expression: "source.output.payment_intent.id"

validations:
  - expression: "source.output.payment_intent.status == 'requires_capture'"
    message: "Payment is not authorized for capture"