# nonk8s
apiVersion: neuron/v1
kind: Project

metadata:
  name: customer-platform
  version: 0.1.0
  description: Customer processing systems

systems:
  entry: ./systems/customer/system.yaml

runtime:
  execution:
    defaultMode: wait
    timeout: 30s

  workers:
    min: 1
    max: 8

storage:
  provider: local

  local:
    directory: ./.neuron/data

executors:
  sources:
    - type: builtin
      name: neuron

    - type: registry
      name: neuron-registry
      url: https://registry.neuron.dev

inspector:
  enabled: true
  address: 127.0.0.1:7433